### ISSUE TITLE
OGP設定

### ISSUE THREAD

**Issue by nobtaka** [nobtaka/ZEEEN_Web#8]
画像作ります。

**Comment by taro-shono** [comment]
@nobtaka 作ったら教えてください。

**Comment by nobtaka** [comment]
Twitterカードもね

**Comment by nobtaka** [comment]
OGPOGP
![ogp](https://cloud.githubusercontent.com/assets/2181405/8304527/b605be8a-19e1-11e5-88f6-4b5bea2155a3.png)
